// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HumidityMonitoring.proto

package grpc.HumidityMonitoringService;

public interface HumidityResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:humidity.HumidityResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double humidityValue = 1;</code>
   */
  double getHumidityValue();
}
