// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HumidityMonitoring.proto

package grpc.HumidityMonitoringService;

public final class HumidityMonitoringServiceImpl {
  private HumidityMonitoringServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_humidity_LocationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_humidity_LocationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_humidity_HumidityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_humidity_HumidityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030HumidityMonitoring.proto\022\010humidity\"%\n\017" +
      "LocationRequest\022\022\n\nlocationID\030\001 \001(\t\")\n\020H" +
      "umidityResponse\022\025\n\rhumidityValue\030\001 \001(\0012\270" +
      "\001\n\031HumidityMonitoringService\022M\n\022GetCurre" +
      "ntHumidity\022\031.humidity.LocationRequest\032\032." +
      "humidity.HumidityResponse\"\000\022L\n\017MonitorHu" +
      "midity\022\031.humidity.LocationRequest\032\032.humi" +
      "dity.HumidityResponse\"\0000\001BA\n\036grpc.Humidi" +
      "tyMonitoringServiceB\035HumidityMonitoringS" +
      "erviceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_humidity_LocationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_humidity_LocationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_humidity_LocationRequest_descriptor,
        new java.lang.String[] { "LocationID", });
    internal_static_humidity_HumidityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_humidity_HumidityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_humidity_HumidityResponse_descriptor,
        new java.lang.String[] { "HumidityValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
