// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HumidityMonitoring.proto

package grpc.HumidityMonitoringService;

public interface LocationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:humidity.LocationRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string locationID = 1;</code>
   */
  java.lang.String getLocationID();
  /**
   * <code>string locationID = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationIDBytes();
}
