// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiskEvaluation.proto

package grpc.RiskEvaluateService;

public interface RiskAssessmentOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RiskEvaluateService.RiskAssessment)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.RiskEvaluateService.RiskAssessment.Level risk_level = 1;</code>
   */
  int getRiskLevelValue();
  /**
   * <code>.RiskEvaluateService.RiskAssessment.Level risk_level = 1;</code>
   */
  grpc.RiskEvaluateService.RiskAssessment.Level getRiskLevel();

  /**
   * <pre>
   * e.g., "High risk detected in Zone A"
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * e.g., "High risk detected in Zone A"
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
