// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiskEvaluation.proto

package grpc.RiskEvaluateService;

/**
 * Protobuf type {@code RiskEvaluateService.RiskAssessment}
 */
public  final class RiskAssessment extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:RiskEvaluateService.RiskAssessment)
    RiskAssessmentOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RiskAssessment.newBuilder() to construct.
  private RiskAssessment(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RiskAssessment() {
    riskLevel_ = 0;
    message_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RiskAssessment(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            riskLevel_ = rawValue;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.RiskEvaluateService.RiskEvaluateServiceImpl.internal_static_RiskEvaluateService_RiskAssessment_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.RiskEvaluateService.RiskEvaluateServiceImpl.internal_static_RiskEvaluateService_RiskAssessment_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.RiskEvaluateService.RiskAssessment.class, grpc.RiskEvaluateService.RiskAssessment.Builder.class);
  }

  /**
   * Protobuf enum {@code RiskEvaluateService.RiskAssessment.Level}
   */
  public enum Level
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOW = 0;</code>
     */
    LOW(0),
    /**
     * <code>MEDIUM = 1;</code>
     */
    MEDIUM(1),
    /**
     * <code>HIGH = 2;</code>
     */
    HIGH(2),
    /**
     * <code>CRITICAL = 3;</code>
     */
    CRITICAL(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LOW = 0;</code>
     */
    public static final int LOW_VALUE = 0;
    /**
     * <code>MEDIUM = 1;</code>
     */
    public static final int MEDIUM_VALUE = 1;
    /**
     * <code>HIGH = 2;</code>
     */
    public static final int HIGH_VALUE = 2;
    /**
     * <code>CRITICAL = 3;</code>
     */
    public static final int CRITICAL_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Level valueOf(int value) {
      return forNumber(value);
    }

    public static Level forNumber(int value) {
      switch (value) {
        case 0: return LOW;
        case 1: return MEDIUM;
        case 2: return HIGH;
        case 3: return CRITICAL;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Level>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Level> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Level>() {
            public Level findValueByNumber(int number) {
              return Level.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return grpc.RiskEvaluateService.RiskAssessment.getDescriptor().getEnumTypes().get(0);
    }

    private static final Level[] VALUES = values();

    public static Level valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Level(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:RiskEvaluateService.RiskAssessment.Level)
  }

  public static final int RISK_LEVEL_FIELD_NUMBER = 1;
  private int riskLevel_;
  /**
   * <code>.RiskEvaluateService.RiskAssessment.Level risk_level = 1;</code>
   */
  public int getRiskLevelValue() {
    return riskLevel_;
  }
  /**
   * <code>.RiskEvaluateService.RiskAssessment.Level risk_level = 1;</code>
   */
  public grpc.RiskEvaluateService.RiskAssessment.Level getRiskLevel() {
    @SuppressWarnings("deprecation")
    grpc.RiskEvaluateService.RiskAssessment.Level result = grpc.RiskEvaluateService.RiskAssessment.Level.valueOf(riskLevel_);
    return result == null ? grpc.RiskEvaluateService.RiskAssessment.Level.UNRECOGNIZED : result;
  }

  public static final int MESSAGE_FIELD_NUMBER = 2;
  private volatile java.lang.Object message_;
  /**
   * <pre>
   * e.g., "High risk detected in Zone A"
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * e.g., "High risk detected in Zone A"
   * </pre>
   *
   * <code>string message = 2;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (riskLevel_ != grpc.RiskEvaluateService.RiskAssessment.Level.LOW.getNumber()) {
      output.writeEnum(1, riskLevel_);
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, message_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (riskLevel_ != grpc.RiskEvaluateService.RiskAssessment.Level.LOW.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, riskLevel_);
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, message_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.RiskEvaluateService.RiskAssessment)) {
      return super.equals(obj);
    }
    grpc.RiskEvaluateService.RiskAssessment other = (grpc.RiskEvaluateService.RiskAssessment) obj;

    boolean result = true;
    result = result && riskLevel_ == other.riskLevel_;
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + RISK_LEVEL_FIELD_NUMBER;
    hash = (53 * hash) + riskLevel_;
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.RiskEvaluateService.RiskAssessment parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.RiskEvaluateService.RiskAssessment parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.RiskEvaluateService.RiskAssessment parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.RiskEvaluateService.RiskAssessment parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.RiskEvaluateService.RiskAssessment parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.RiskEvaluateService.RiskAssessment parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.RiskEvaluateService.RiskAssessment parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.RiskEvaluateService.RiskAssessment parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.RiskEvaluateService.RiskAssessment parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.RiskEvaluateService.RiskAssessment parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.RiskEvaluateService.RiskAssessment parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.RiskEvaluateService.RiskAssessment parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.RiskEvaluateService.RiskAssessment prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code RiskEvaluateService.RiskAssessment}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:RiskEvaluateService.RiskAssessment)
      grpc.RiskEvaluateService.RiskAssessmentOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.RiskEvaluateService.RiskEvaluateServiceImpl.internal_static_RiskEvaluateService_RiskAssessment_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.RiskEvaluateService.RiskEvaluateServiceImpl.internal_static_RiskEvaluateService_RiskAssessment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.RiskEvaluateService.RiskAssessment.class, grpc.RiskEvaluateService.RiskAssessment.Builder.class);
    }

    // Construct using grpc.RiskEvaluateService.RiskAssessment.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      riskLevel_ = 0;

      message_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.RiskEvaluateService.RiskEvaluateServiceImpl.internal_static_RiskEvaluateService_RiskAssessment_descriptor;
    }

    @java.lang.Override
    public grpc.RiskEvaluateService.RiskAssessment getDefaultInstanceForType() {
      return grpc.RiskEvaluateService.RiskAssessment.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.RiskEvaluateService.RiskAssessment build() {
      grpc.RiskEvaluateService.RiskAssessment result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.RiskEvaluateService.RiskAssessment buildPartial() {
      grpc.RiskEvaluateService.RiskAssessment result = new grpc.RiskEvaluateService.RiskAssessment(this);
      result.riskLevel_ = riskLevel_;
      result.message_ = message_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.RiskEvaluateService.RiskAssessment) {
        return mergeFrom((grpc.RiskEvaluateService.RiskAssessment)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.RiskEvaluateService.RiskAssessment other) {
      if (other == grpc.RiskEvaluateService.RiskAssessment.getDefaultInstance()) return this;
      if (other.riskLevel_ != 0) {
        setRiskLevelValue(other.getRiskLevelValue());
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.RiskEvaluateService.RiskAssessment parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.RiskEvaluateService.RiskAssessment) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int riskLevel_ = 0;
    /**
     * <code>.RiskEvaluateService.RiskAssessment.Level risk_level = 1;</code>
     */
    public int getRiskLevelValue() {
      return riskLevel_;
    }
    /**
     * <code>.RiskEvaluateService.RiskAssessment.Level risk_level = 1;</code>
     */
    public Builder setRiskLevelValue(int value) {
      riskLevel_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.RiskEvaluateService.RiskAssessment.Level risk_level = 1;</code>
     */
    public grpc.RiskEvaluateService.RiskAssessment.Level getRiskLevel() {
      @SuppressWarnings("deprecation")
      grpc.RiskEvaluateService.RiskAssessment.Level result = grpc.RiskEvaluateService.RiskAssessment.Level.valueOf(riskLevel_);
      return result == null ? grpc.RiskEvaluateService.RiskAssessment.Level.UNRECOGNIZED : result;
    }
    /**
     * <code>.RiskEvaluateService.RiskAssessment.Level risk_level = 1;</code>
     */
    public Builder setRiskLevel(grpc.RiskEvaluateService.RiskAssessment.Level value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      riskLevel_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.RiskEvaluateService.RiskAssessment.Level risk_level = 1;</code>
     */
    public Builder clearRiskLevel() {
      
      riskLevel_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object message_ = "";
    /**
     * <pre>
     * e.g., "High risk detected in Zone A"
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * e.g., "High risk detected in Zone A"
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * e.g., "High risk detected in Zone A"
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g., "High risk detected in Zone A"
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * e.g., "High risk detected in Zone A"
     * </pre>
     *
     * <code>string message = 2;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:RiskEvaluateService.RiskAssessment)
  }

  // @@protoc_insertion_point(class_scope:RiskEvaluateService.RiskAssessment)
  private static final grpc.RiskEvaluateService.RiskAssessment DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.RiskEvaluateService.RiskAssessment();
  }

  public static grpc.RiskEvaluateService.RiskAssessment getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RiskAssessment>
      PARSER = new com.google.protobuf.AbstractParser<RiskAssessment>() {
    @java.lang.Override
    public RiskAssessment parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RiskAssessment(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RiskAssessment> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RiskAssessment> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.RiskEvaluateService.RiskAssessment getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

