// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RiskEvaluation.proto

package grpc.RiskEvaluateService;

public interface EnvironmentalDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:RiskEvaluateService.EnvironmentalData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double tempValue = 1;</code>
   */
  double getTempValue();

  /**
   * <code>double humidityValue = 2;</code>
   */
  double getHumidityValue();

  /**
   * <code>string locationID = 3;</code>
   */
  java.lang.String getLocationID();
  /**
   * <code>string locationID = 3;</code>
   */
  com.google.protobuf.ByteString
      getLocationIDBytes();
}
