// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyResponse.proto

package grpc.EmergencyResponseService;

public interface ActionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyResponseService.ActionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
