// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyResponse.proto

package grpc.EmergencyResponseService;

public final class EmergencyResponseServiceImpl {
  private EmergencyResponseServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmergencyResponseService_ActionRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmergencyResponseService_ActionRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmergencyResponseService_ActionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmergencyResponseService_ActionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmergencyResponseService_DeviceHealthRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmergencyResponseService_DeviceHealthRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_EmergencyResponseService_DeviceStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_EmergencyResponseService_DeviceStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027EmergencyResponse.proto\022\030EmergencyResp" +
      "onseService\"3\n\rActionRequest\022\020\n\010location" +
      "\030\001 \001(\t\022\020\n\010activate\030\002 \001(\010\"2\n\016ActionRespon" +
      "se\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001(\t\"\'\n\023" +
      "DeviceHealthRequest\022\020\n\010deviceID\030\001 \001(\t\"8\n" +
      "\024DeviceStatusResponse\022\020\n\010deviceID\030\001 \001(\t\022" +
      "\016\n\006status\030\002 \001(\t2\201\002\n\030EmergencyResponseSer" +
      "vice\022i\n\022ActivateSprinklers\022\'.EmergencyRe" +
      "sponseService.ActionRequest\032(.EmergencyR" +
      "esponseService.ActionResponse\"\000\022z\n\023Monit" +
      "orDeviceStatus\022-.EmergencyResponseServic" +
      "e.DeviceHealthRequest\032..EmergencyRespons" +
      "eService.DeviceStatusResponse\"\000(\0010\001B?\n\035g" +
      "rpc.EmergencyResponseServiceB\034EmergencyR" +
      "esponseServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_EmergencyResponseService_ActionRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_EmergencyResponseService_ActionRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmergencyResponseService_ActionRequest_descriptor,
        new java.lang.String[] { "Location", "Activate", });
    internal_static_EmergencyResponseService_ActionResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_EmergencyResponseService_ActionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmergencyResponseService_ActionResponse_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_EmergencyResponseService_DeviceHealthRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_EmergencyResponseService_DeviceHealthRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmergencyResponseService_DeviceHealthRequest_descriptor,
        new java.lang.String[] { "DeviceID", });
    internal_static_EmergencyResponseService_DeviceStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_EmergencyResponseService_DeviceStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_EmergencyResponseService_DeviceStatusResponse_descriptor,
        new java.lang.String[] { "DeviceID", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
