// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureMonitoring.proto

package grpc.TempMonitoringService;

public final class TempMonitoringServiceImpl {
  private TempMonitoringServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TempMonitoringService_LocationRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TempMonitoringService_LocationRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TempMonitoringService_TemperatureResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TempMonitoringService_TemperatureResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033TemperatureMonitoring.proto\022\025TempMonit" +
      "oringService\"%\n\017LocationRequest\022\022\n\nlocat" +
      "ionID\030\001 \001(\t\";\n\023TemperatureResponse\022\021\n\tte" +
      "mpValue\030\001 \001(\001\022\021\n\ttimeStamp\030\002 \001(\0052\364\001\n\025Tem" +
      "pMonitoringService\022m\n\025GetCurrentTemperat" +
      "ure\022&.TempMonitoringService.LocationRequ" +
      "est\032*.TempMonitoringService.TemperatureR" +
      "esponse\"\000\022l\n\022MonitorTemperature\022&.TempMo" +
      "nitoringService.LocationRequest\032*.TempMo" +
      "nitoringService.TemperatureResponse\"\0000\001B" +
      "9\n\032grpc.TempMonitoringServiceB\031TempMonit" +
      "oringServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_TempMonitoringService_LocationRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TempMonitoringService_LocationRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TempMonitoringService_LocationRequest_descriptor,
        new java.lang.String[] { "LocationID", });
    internal_static_TempMonitoringService_TemperatureResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TempMonitoringService_TemperatureResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TempMonitoringService_TemperatureResponse_descriptor,
        new java.lang.String[] { "TempValue", "TimeStamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
