// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureMonitoring.proto

package grpc.TempMonitoringService;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TempMonitoringService.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 tempValue = 1;</code>
   */
  int getTempValue();
}
