// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyResponse.proto

package grpc.EmergencyResponseService;

public interface ActionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyResponseService.ActionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string location = 1;</code>
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 1;</code>
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>bool activate = 2;</code>
   */
  boolean getActivate();
}
