// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyResponse.proto

package grpc.EmergencyResponseService;

public interface DeviceStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyResponseService.DeviceStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deviceID = 1;</code>
   */
  java.lang.String getDeviceID();
  /**
   * <code>string deviceID = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIDBytes();

  /**
   * <pre>
   * e.g., "Working", "Blocked", "Empty"
   * </pre>
   *
   * <code>string status = 2;</code>
   */
  java.lang.String getStatus();
  /**
   * <pre>
   * e.g., "Working", "Blocked", "Empty"
   * </pre>
   *
   * <code>string status = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
