// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EmergencyResponse.proto

package grpc.EmergencyResponseService;

public interface DeviceHealthRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmergencyResponseService.DeviceHealthRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string deviceID = 1;</code>
   */
  java.lang.String getDeviceID();
  /**
   * <code>string deviceID = 1;</code>
   */
  com.google.protobuf.ByteString
      getDeviceIDBytes();
}
