// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureMonitoring.proto

package grpc.TempMonitoringService;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TempMonitoringService.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double tempValue = 1;</code>
   */
  double getTempValue();

  /**
   * <code>int32 timeStamp = 2;</code>
   */
  int getTimeStamp();
}
